export { createTheSvgIcon, type TheSvgIconModule } from "./thesvg-icon"
export { WordIcon } from "./word-icon"
export { ExcelIcon } from "./excel-icon"
export { PowerPointIcon } from "./powerpoint-icon"
export { PdfIcon } from "./pdf-icon"
export { ImageIcon } from "./image-icon"
export { VideoIcon } from "./video-icon"
export { AudioIcon } from "./audio-icon"
export { ArchiveIcon } from "./archive-icon"
export { CodeIcon } from "./code-icon"
export { TxtIcon } from "./txt-icon"
export { GenericDocIcon } from "./generic-doc-icon"
