/** AUTO-GENERATED — materialize từ @workspace/api-server/deploy/nest. Chạy: pnpm api:render */
import {
  EVENT_CHECKIN_STAFF_PERMISSIONS,
  EVENT_STAFF_ROLE_TEMPLATE,
} from '../config/role-templates/event-staff.template';

// Role data — mật khẩu plain `demo` (chỉ local / seed dev).
export const DEV_LOGIN_PASSWORD_PLAIN = 'demo';

export const DEV_LOGIN_PASSWORD_HASH =
  '$2b$10$6gktuaAnT51RIaAhhkRozOYZpg664aG.B03tp/VQ0x7BlOVgXbE1y';

export { EVENT_CHECKIN_STAFF_PERMISSIONS, EVENT_STAFF_ROLE_TEMPLATE };

export const SUPERADMIN_ROLES_DATA = [
  {
    name: 'super_admin',
    displayName: 'Super Admin',
    description: '',
    permissions: [
      'accounts:update',
      'accounts:manage',
      'accounts:view',
      'admission_results:update',
      'admission_results:export',
      'admission_results:import',
      'admission_results:manage',
      'admission_results:restore',
      'admission_results:create',
      'admission_results:view',
      'admission_results:delete',
      'posts:update',
      'posts:export',
      'posts:import',
      'posts:manage',
      'posts:restore',
      'posts:create',
      'posts:view_all',
      'posts:view_own',
      'posts:view',
      'posts:delete',
      'posts:publish',
      'comments:update',
      'comments:approve',
      'comments:export',
      'comments:manage',
      'comments:restore',
      'comments:create',
      'comments:view',
      'comments:delete',
      'settings:update',
      'settings:export',
      'settings:manage',
      'settings:create',
      'settings:view',
      'settings:delete',
      'categories:update',
      'categories:export',
      'categories:manage',
      'categories:create',
      'categories:view',
      'categories:delete',
      'categories:restore',
      'categories:hard-delete',
      'dashboard:view',
      'groups:update',
      'groups:export',
      'groups:manage',
      'groups:create',
      'groups:view',
      'groups:delete',
      'groups:restore',
      'groups:hard-delete',
      'contact_requests:update',
      'contact_requests:export',
      'contact_requests:assign',
      'contact_requests:manage',
      'contact_requests:restore',
      'contact_requests:create',
      'contact_requests:view',
      'contact_requests:delete',
      'users:active',
      'users:update',
      'users:export',
      'users:hard-delete',
      'users:import',
      'users:manage',
      'users:restore',
      'users:create',
      'users:unactive',
      'users:view',
      'users:delete',
      'page_contents:update',
      'page_contents:export',
      'page_contents:manage',
      'page_contents:create',
      'page_contents:view',
      'page_contents:delete',
      'sessions:update',
      'sessions:export',
      'sessions:manage',
      'sessions:restore',
      'sessions:revoke-by-user',
      'sessions:create',
      'sessions:view',
      'sessions:delete',
      'students:active',
      'students:update',
      'students:export',
      'students:import',
      'students:manage',
      'students:restore',
      'students:create',
      'students:view_all',
      'students:view_own',
      'students:view',
      'students:delete',
      'tags:update',
      'tags:export',
      'tags:manage',
      'tags:restore',
      'tags:create',
      'tags:view',
      'tags:delete',
      'notifications:export',
      'notifications:manage',
      'notifications:view_all',
      'notifications:view_own',
      'notifications:view',
      'messages:update',
      'messages:export',
      'messages:manage',
      'messages:create',
      'messages:view',
      'messages:delete',
      'uploads:update',
      'uploads:export',
      'uploads:manage',
      'uploads:create',
      'uploads:view',
      'uploads:delete',
      'roles:update',
      'roles:export',
      'roles:manage',
      'roles:create',
      'roles:view',
      'roles:delete',
      'roles:restore',
      'imported_users:view',
      'imported_users:create',
      'imported_users:update',
      'imported_users:delete',
      'imported_users:manage',
      'imported_users:export',
      'imported_users:restore',
      'system:view',
      'system:create',
      'system:update',
      'system:delete',
      'system:manage',
      'system:export',
      'system:import',
      'parent_students:view',
      'parent_students:create',
      'parent_students:update',
      'parent_students:delete',
      'parent_students:manage',
      'parent_students:export',
      'products:view',
      'products:create',
      'products:update',
      'products:delete',
      'products:manage',
      'products:export',
      'products:restore',
      'orders:view',
      'orders:create',
      'orders:update',
      'orders:delete',
      'orders:manage',
      'orders:export',
      'orders:checkout',
      'promo_codes:view',
      'promo_codes:create',
      'promo_codes:update',
      'promo_codes:delete',
      'promo_codes:manage',
      'promo_codes:export',
    ],
    isActive: true,
  },
  {
    name: 'admin',
    displayName: 'Admin',
    description: null,
    permissions: [
      'dashboard:view',
      'posts:view',
      'posts:view_all',
      'posts:view_own',
      'posts:create',
      'posts:update',
      'posts:delete',
      'posts:publish',
      'posts:manage',
      'categories:view',
      'categories:create',
      'categories:update',
      'categories:delete',
      'categories:restore',
      'categories:hard-delete',
      'categories:manage',
      'users:view',
      'users:create',
      'users:update',
      'users:delete',
      'users:manage',
      'notifications:view',
      'notifications:view_all',
      'notifications:view_own',
      'notifications:manage',
      'contact_requests:view',
      'contact_requests:create',
      'contact_requests:assign',
      'contact_requests:update',
      'contact_requests:delete',
      'contact_requests:manage',
      'accounts:view',
      'accounts:update',
      'sessions:view',
      'sessions:create',
      'sessions:update',
      'sessions:delete',
      'sessions:manage',
      'uploads:view',
      'uploads:create',
      'uploads:delete',
      'uploads:manage',
      'admission_results:view',
      'admission_results:create',
      'admission_results:update',
      'admission_results:delete',
      'admission_results:manage',
      'page_contents:view',
      'page_contents:create',
      'page_contents:update',
      'page_contents:delete',
      'page_contents:manage',
      'groups:view',
      'groups:create',
      'groups:update',
      'groups:delete',
      'groups:restore',
      'groups:hard-delete',
      'groups:manage',
      'settings:view',
      'settings:manage',
      'settings:import',
      'settings:export',
      'settings:update',
      'products:view',
      'products:create',
      'products:update',
      'products:delete',
      'products:manage',
      'orders:view',
      'orders:update',
      'orders:manage',
      'orders:checkout',
      'promo_codes:view',
      'promo_codes:create',
      'promo_codes:update',
      'promo_codes:manage',
    ],
    isActive: true,
  },
  {
    name: 'editor',
    displayName: 'Editor',
    description: '',
    permissions: [
      'posts:view',
      'posts:create',
      'posts:update',
      'posts:delete',
      'posts:export',
      'posts:import',
      'posts:manage',
      'posts:publish',
      'posts:restore',
      'posts:view_all',
      'posts:view_own',
      'accounts:view',
      'accounts:update',
      'accounts:manage',
      'dashboard:view',
      'uploads:view',
      'uploads:create',
      'uploads:update',
      'uploads:delete',
      'uploads:export',
      'uploads:manage',
      'categories:view',
      'categories:create',
      'categories:update',
      'categories:delete',
      'categories:restore',
      'categories:hard-delete',
      'categories:export',
      'categories:manage',
      'tags:view',
      'tags:create',
      'tags:update',
      'tags:delete',
      'tags:export',
      'tags:manage',
      'contact_requests:view',
      'contact_requests:create',
      'contact_requests:update',
      'contact_requests:delete',
      'contact_requests:assign',
      'contact_requests:export',
      'contact_requests:manage',
      'contact_requests:restore',
      'page_contents:view',
      'page_contents:create',
      'page_contents:update',
      'page_contents:delete',
      'page_contents:export',
      'page_contents:manage',
    ],
    isActive: true,
  },
  {
    name: 'user',
    displayName: 'User',
    description: null,
    permissions: null,
    isActive: true,
  },
  {
    name: 'parent',
    displayName: 'Phụ huynh',
    description: 'Tài khoản phụ huynh — liên kết và theo dõi học sinh',
    permissions: [
      'dashboard:view',
      'parent_students:view',
      'parent_students:create',
      'notifications:view_own',
      'messages:view_own',
      'posts:view',
      'accounts:view',
      'accounts:update',
    ],
    isActive: true,
  },
  {
    name: 'student',
    displayName: 'Sinh viên',
    description:
      'Tài khoản sinh viên — xem thông tin cá nhân, thông báo và bài viết',
    permissions: [
      'dashboard:view',
      'students:view_own',
      'notifications:view_own',
      'messages:view_own',
      'posts:view',
      'accounts:view',
      'accounts:update',
    ],
    isActive: true,
  },
  { ...EVENT_STAFF_ROLE_TEMPLATE },
];

// User data
export const SUPERADMIN_USERS_DATA = [
  {
    email: 'superadmin@hub.edu.vn',
    name: 'Super Administrator',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: null,
    avatar: null,
    emailVerified: null,
    phone: null,
    address: null,
    isActive: true,
  },
  {
    email: 'admin@hub.edu.vn',
    name: 'Administrator',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: null,
    avatar: null,
    emailVerified: null,
    phone: null,
    address: null,
    isActive: true,
  },
  {
    email: 'lamvtt@hub.edu.vn',
    name: 'Thanh Lâm',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: '',
    avatar: null,
    emailVerified: null,
    phone: '',
    address: null,
    isActive: true,
  },
  {
    email: 'thang.ph2146@gmail.com',
    name: 'Thắng Phạm',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: '',
    avatar:
      'https://lh3.googleusercontent.com/a/ACg8ocLhicj6TqxKzF0hVnmJ5OueMMe-zdEgZT_U9b3iIzjTQP3ZerqO=s96-c',
    emailVerified: null,
    phone: '',
    address: null,
    isActive: true,
  },
  {
    email: 'thangph@hub.edu.vn',
    name: 'Thang Pham Hoang',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: '',
    avatar:
      'https://lh3.googleusercontent.com/a/ACg8ocK8ybfPbsmaejqRrCM1q1hKxnsAi5KclkMWiMmEdb3Q2KveHw=s96-c',
    emailVerified: null,
    phone: '',
    address: null,
    isActive: true,
  },
  {
    email: 'student@hub.edu.vn',
    name: 'Nguyễn Văn A',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: null,
    avatar: null,
    emailVerified: null,
    phone: '0123456789',
    address: 'Khu phố 6, Thủ Đức, TP.HCM',
    isActive: true,
  },
  {
    email: 'demo.sv@st.buh.edu.vn',
    name: 'Sinh viên demo (check-in)',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: null,
    avatar: null,
    emailVerified: null,
    phone: null,
    address: null,
    isActive: true,
  },
  {
    email: 'demo.phuhuynh@hub.edu.vn',
    name: 'Phụ huynh demo (check-in)',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: null,
    avatar: null,
    emailVerified: null,
    phone: null,
    address: null,
    isActive: true,
  },
  {
    email: 'demo.khach@hub.edu.vn',
    name: 'Khách demo (check-in)',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: null,
    avatar: null,
    emailVerified: null,
    phone: null,
    address: null,
    isActive: true,
  },
  {
    email: 'btc.checkin@hub.edu.vn',
    name: 'BTC Check-in (demo)',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: 'Ban tổ chức (BTC) — cổng /admin, role event_staff',
    avatar: null,
    emailVerified: null,
    phone: null,
    address: null,
    isActive: true,
  },
];

// UserRole data
export const SUPERADMIN_USER_ROLES_DATA = [
  { userEmail: 'superadmin@hub.edu.vn', roleName: 'super_admin' },
  { userEmail: 'admin@hub.edu.vn', roleName: 'admin' },
  { userEmail: 'lamvtt@hub.edu.vn', roleName: 'editor' },
  { userEmail: 'thang.ph2146@gmail.com', roleName: 'editor' },
  { userEmail: 'thangph@hub.edu.vn', roleName: 'editor' },
  { userEmail: 'student@hub.edu.vn', roleName: 'student' },
  { userEmail: 'demo.sv@st.buh.edu.vn', roleName: 'student' },
  { userEmail: 'demo.phuhuynh@hub.edu.vn', roleName: 'parent' },
  { userEmail: 'demo.khach@hub.edu.vn', roleName: 'user' },
  { userEmail: 'btc.checkin@hub.edu.vn', roleName: 'event_staff' },
];
