/** Tài liệu chính thức HANET Partner API (Postman). */
export const HANET_POSTMAN_DOCS_URL =
  "https://documenter.getpostman.com/view/13088306/TVeqcn2C"

export const HANET_PARTNER_API_BASE = "https://partner.hanet.ai"

export type HanetPartnerEndpoint = {
  /** Nhóm trong Postman collection */
  group: string
  /** HTTP method trên partner.hanet.ai (OAuth dùng GET authorize) */
  partnerMethod: "POST" | "GET"
  partnerPath: string
  /** Proxy admin Hub — bỏ trống nếu chỉ gọi trực tiếp partner / webhook */
  hubMethod?: "GET" | "POST" | "PATCH" | "DELETE"
  hubPath?: string
}

export const HANET_PARTNER_ENDPOINTS = {
  oauthAuthorize: {
    group: "OAuth",
    partnerMethod: "GET",
    partnerPath: "/oauth2/authorize",
    hubMethod: "GET",
    hubPath: "/admin/hanet/status",
  },
  oauthToken: {
    group: "OAuth",
    partnerMethod: "POST",
    partnerPath: "/token",
    hubMethod: "POST",
    hubPath: "/admin/hanet/test-connection",
  },
  partnerUpdateToken: {
    group: "Partner",
    partnerMethod: "POST",
    partnerPath: "/partner/updateToken",
    hubMethod: "POST",
    hubPath: "/admin/hanet/partner/update-token",
  },
  partnerAddPlacePartner: {
    group: "Partner",
    partnerMethod: "POST",
    partnerPath: "/partner/addPlacePartner",
    hubMethod: "POST",
    hubPath: "/admin/hanet/places",
  },
  partnerRemovePlacePartner: {
    group: "Partner",
    partnerMethod: "POST",
    partnerPath: "/partner/removePlacePartner",
    hubMethod: "DELETE",
    hubPath: "/admin/hanet/places?placeId=",
  },
  partnerRemoveUserPartner: {
    group: "Partner",
    partnerMethod: "POST",
    partnerPath: "/partner/removeUserPartner",
    hubMethod: "DELETE",
    hubPath: "/admin/hanet/partner/users?clientId=",
  },
  partnerGetListUserPartner: {
    group: "Partner",
    partnerMethod: "POST",
    partnerPath: "/partner/getListUserPartner",
    hubMethod: "GET",
    hubPath: "/admin/hanet/partner/users",
  },
  profile: {
    group: "Profile",
    partnerMethod: "POST",
    partnerPath: "/profile/getProfile",
    hubMethod: "GET",
    hubPath: "/admin/hanet/profile",
  },
  profileTest: {
    group: "Profile",
    partnerMethod: "POST",
    partnerPath: "/profile/getProfile",
    hubMethod: "POST",
    hubPath: "/admin/hanet/test-partner",
  },
  places: {
    group: "Place",
    partnerMethod: "POST",
    partnerPath: "/place/getPlaces",
    hubMethod: "GET",
    hubPath: "/admin/hanet/places",
  },
  placeAdd: {
    group: "Place",
    partnerMethod: "POST",
    partnerPath: "/place/addPlace",
    hubMethod: "POST",
    hubPath: "/admin/hanet/places",
  },
  placeUpdate: {
    group: "Place",
    partnerMethod: "POST",
    partnerPath: "/place/updatePlace",
    hubMethod: "PATCH",
    hubPath: "/admin/hanet/places",
  },
  placeRemove: {
    group: "Place",
    partnerMethod: "POST",
    partnerPath: "/place/removePlace",
    hubMethod: "DELETE",
    hubPath: "/admin/hanet/places?placeId=",
  },
  placeInfo: {
    group: "Place",
    partnerMethod: "POST",
    partnerPath: "/place/getPlaceInfo",
    hubMethod: "GET",
    hubPath: "/admin/hanet/places/info?placeId=",
  },
  devices: {
    group: "Device",
    partnerMethod: "POST",
    partnerPath: "/device/getListDeviceByPlace",
    hubMethod: "GET",
    hubPath: "/admin/hanet/devices?placeId=",
  },
  deviceInfo: {
    group: "Device",
    partnerMethod: "POST",
    partnerPath: "/device/getDeviceInfo",
    hubMethod: "GET",
    hubPath: "/admin/hanet/devices/info?deviceId=",
  },
  deviceUpdate: {
    group: "Device",
    partnerMethod: "POST",
    partnerPath: "/device/updateDevice",
    hubMethod: "PATCH",
    hubPath: "/admin/hanet/devices",
  },
  deviceMqtt: {
    group: "Device",
    partnerMethod: "POST",
    partnerPath: "/device/setDeviceMQTT",
    hubMethod: "POST",
    hubPath: "/admin/hanet/devices/mqtt",
  },
  deviceStatus: {
    group: "Device",
    partnerMethod: "POST",
    partnerPath: "/device/getConnectionStatus",
    hubMethod: "GET",
    hubPath: "/admin/hanet/devices/connection-status?deviceId=",
  },
  hubCamerasEnsure: {
    group: "Hub",
    partnerMethod: "POST",
    partnerPath: "/device/getListDeviceByPlace",
    hubMethod: "POST",
    hubPath: "/admin/hanet/cameras/ensure",
  },
  persons: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getListByPlace",
    hubMethod: "GET",
    hubPath: "/admin/hanet/persons?placeId=&pageIndex=&pageSize=",
  },
  personsTotal: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getTotalPersonByPlaceID",
    hubMethod: "GET",
    hubPath: "/admin/hanet/persons?placeId=",
  },
  personRegister: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/register",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/register",
  },
  registerByUrl: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/registerByUrl",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/register-by-url",
  },
  personUpdateByFaceImage: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/updateByFaceImage",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/face/update-by-image",
  },
  personUpdateByFaceImageByAliasID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/updateByFaceImageByAliasID",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/face/update-by-image-by-alias-id",
  },
  personUpdateByFaceImageByPersonID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/updateByFaceImageByPersonID",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/face/update-by-image-by-person-id",
  },
  personUpdateByFaceUrl: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/updateByFaceUrl",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/face/update-by-url",
  },
  personUpdateByFaceUrlByAliasID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/updateByFaceUrlByAliasID",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/face/update-by-url-by-alias-id",
  },
  personUpdateByFaceUrlByPersonID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/updateByFaceUrlByPersonID",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/face/update-by-url-by-person-id",
  },
  personGetListByAliasIDAllPlace: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getListByAliasIDAllPlace",
    hubMethod: "GET",
    hubPath: "/admin/hanet/person/by-alias-all?aliasId=",
  },
  personGetListByAliasID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getListByAliasID",
    hubMethod: "GET",
    hubPath: "/admin/hanet/person/by-alias?aliasId=&placeId=",
  },
  personGetUserInfoByAliasID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getUserInfoByAliasID",
    hubMethod: "GET",
    hubPath: "/admin/hanet/person/user-by-alias?aliasId=&placeId=",
  },
  personGetUserInfoByPersonID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getUserInfoByPersonID",
    hubMethod: "GET",
    hubPath: "/admin/hanet/person/user-by-id?personId=&placeId=",
  },
  personRemove: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/remove",
    hubMethod: "DELETE",
    hubPath: "/admin/hanet/person?personId=&placeId=",
  },
  personRemoveByPlace: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/removeByPlace",
    hubMethod: "DELETE",
    hubPath: "/admin/hanet/person/by-place?aliasId=&placeId=",
  },
  personRemovePersonByListAliasID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/removePersonByListAliasID",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/remove-by-alias-ids",
  },
  personRemoveAllPersonInPlace: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/removeAllPersonInPlace",
    hubMethod: "DELETE",
    hubPath: "/admin/hanet/person/in-place?placeId=",
  },
  personRemovePersonByID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/removePersonByID",
    hubMethod: "DELETE",
    hubPath: "/admin/hanet/person/by-id?personId=&placeId=",
  },
  personUpdate: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/update",
    hubMethod: "PATCH",
    hubPath: "/admin/hanet/person",
  },
  personUpdateInfo: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/updateInfo",
    hubMethod: "PATCH",
    hubPath: "/admin/hanet/person/info",
  },
  personUpdateAliasID: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/updateAliasID",
    hubMethod: "PATCH",
    hubPath: "/admin/hanet/person/alias-id",
  },
  personTakeFacePicture: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/takeFacePicture",
    hubMethod: "POST",
    hubPath: "/admin/hanet/person/face/take-picture",
  },
  hubPersonsSync: {
    group: "Hub",
    partnerMethod: "POST",
    partnerPath: "/person/getListByPlace",
    hubMethod: "POST",
    hubPath: "/admin/hanet/persons/sync?placeId=",
  },
  hubAvatars: {
    group: "Hub",
    partnerMethod: "POST",
    partnerPath: "/person/getListByPlace",
    hubMethod: "GET",
    hubPath: "/admin/hanet/avatars?page=&limit=&search=",
  },
  checkins: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getCheckinByPlaceIdInDay",
    hubMethod: "GET",
    hubPath: "/admin/hanet/checkins?placeId=&date=",
  },
  checkinTotal: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getTotalCheckinByPlaceIdInDay",
    hubMethod: "GET",
    hubPath: "/admin/hanet/checkins?placeId=&date=",
  },
  checkinTimestamp: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getCheckinByPlaceIdInTimestamp",
    hubMethod: "GET",
    hubPath: "/admin/hanet/checkins/timestamp?placeId=&from=&to=",
  },
  checkinTotalTimestamp: {
    group: "Person",
    partnerMethod: "POST",
    partnerPath: "/person/getTotalCheckinByPlaceIdInTimestamp",
    hubMethod: "GET",
    hubPath: "/admin/hanet/checkins/timestamp?placeId=&from=&to=",
  },
} as const satisfies Record<string, HanetPartnerEndpoint>

/** Endpoint Postman theo từng trang admin HANET. */
export const HANET_PAGE_ENDPOINTS = {
  ketNoi: [
    HANET_PARTNER_ENDPOINTS.oauthAuthorize,
    HANET_PARTNER_ENDPOINTS.oauthToken,
    HANET_PARTNER_ENDPOINTS.partnerUpdateToken,
    HANET_PARTNER_ENDPOINTS.partnerAddPlacePartner,
    HANET_PARTNER_ENDPOINTS.partnerRemovePlacePartner,
    HANET_PARTNER_ENDPOINTS.partnerRemoveUserPartner,
    HANET_PARTNER_ENDPOINTS.partnerGetListUserPartner,
    HANET_PARTNER_ENDPOINTS.profile,
    HANET_PARTNER_ENDPOINTS.profileTest,
  ],
  diaDiem: [
    HANET_PARTNER_ENDPOINTS.places,
    HANET_PARTNER_ENDPOINTS.placeAdd,
    HANET_PARTNER_ENDPOINTS.placeUpdate,
    HANET_PARTNER_ENDPOINTS.placeRemove,
    HANET_PARTNER_ENDPOINTS.placeInfo,
  ],
  thietBi: [
    HANET_PARTNER_ENDPOINTS.devices,
    HANET_PARTNER_ENDPOINTS.deviceInfo,
    HANET_PARTNER_ENDPOINTS.deviceUpdate,
    HANET_PARTNER_ENDPOINTS.deviceMqtt,
    HANET_PARTNER_ENDPOINTS.deviceStatus,
    HANET_PARTNER_ENDPOINTS.hubCamerasEnsure,
  ],
  nguoi: [
    HANET_PARTNER_ENDPOINTS.persons,
    HANET_PARTNER_ENDPOINTS.personsTotal,
    HANET_PARTNER_ENDPOINTS.personRegister,
    HANET_PARTNER_ENDPOINTS.registerByUrl,
    HANET_PARTNER_ENDPOINTS.personGetListByAliasIDAllPlace,
    HANET_PARTNER_ENDPOINTS.personGetListByAliasID,
    HANET_PARTNER_ENDPOINTS.personGetUserInfoByAliasID,
    HANET_PARTNER_ENDPOINTS.personGetUserInfoByPersonID,
    HANET_PARTNER_ENDPOINTS.personUpdate,
    HANET_PARTNER_ENDPOINTS.personUpdateInfo,
    HANET_PARTNER_ENDPOINTS.personUpdateAliasID,
    HANET_PARTNER_ENDPOINTS.personRemove,
    HANET_PARTNER_ENDPOINTS.personRemoveByPlace,
    HANET_PARTNER_ENDPOINTS.personRemovePersonByListAliasID,
    HANET_PARTNER_ENDPOINTS.personRemoveAllPersonInPlace,
    HANET_PARTNER_ENDPOINTS.personRemovePersonByID,
  ],
  avatar: [
    HANET_PARTNER_ENDPOINTS.persons,
    HANET_PARTNER_ENDPOINTS.personsTotal,
    HANET_PARTNER_ENDPOINTS.hubPersonsSync,
    HANET_PARTNER_ENDPOINTS.hubAvatars,
    HANET_PARTNER_ENDPOINTS.personUpdateByFaceImage,
    HANET_PARTNER_ENDPOINTS.personUpdateByFaceImageByAliasID,
    HANET_PARTNER_ENDPOINTS.personUpdateByFaceImageByPersonID,
    HANET_PARTNER_ENDPOINTS.personUpdateByFaceUrl,
    HANET_PARTNER_ENDPOINTS.personUpdateByFaceUrlByAliasID,
    HANET_PARTNER_ENDPOINTS.personUpdateByFaceUrlByPersonID,
    HANET_PARTNER_ENDPOINTS.personTakeFacePicture,
    HANET_PARTNER_ENDPOINTS.registerByUrl,
  ],
  checkin: [
    HANET_PARTNER_ENDPOINTS.checkins,
    HANET_PARTNER_ENDPOINTS.checkinTotal,
    HANET_PARTNER_ENDPOINTS.checkinTimestamp,
    HANET_PARTNER_ENDPOINTS.checkinTotalTimestamp,
  ],
} as const satisfies Record<string, readonly HanetPartnerEndpoint[]>
